Update requirements
 - Move pytest to pip in conda environment because conda doesn't have the required version,
 - Set a max version for sphinx because of a bug resulting in an error:
   'NoneType' object has no attribute 'registry'